### ISSUE TITLE
Location /nr2id.php lead to 404

### ISSUE THREAD

**Issue by kumy** [GeoKretyMap/gkm-api-nginx#2]
Accessing: `https://api.geokretymap.org/nr2id.php?nr=X534GL` gives a 404 error.
Logs:

```
api.geokretymap.org 62.212.123.32 - - [31/Aug/2016:20:01:36 +0000] "GET /nr2id.php?nr=X534GL HTTP/1.1" 404 169 "-" "curl/7.43.0" 0.000 - .
2016/08/31 20:01:36 [error] 33#33: *1705 open() "/var/www/html/nr2id/X534GL" failed (2: No such file or directory), client: 172.18.0.9, server: ~^api\..+$, request: "GET /nr2id.php?nr=X534GL HTTP/1.1", host: "api.geokretymap.org"
```

Relevant part of conf:

```
# main entrypoint                                  
location = /select.php {
    limit_req   zone=one_per_sec  burst=50 nodelay;
}

rewrite ^/nr2id/([a-zA-Z0-9]+)/?$ /select.php?nr=$1&nr2id=true last;

location = /nr2id.php {
    rewrite ^/nr2id.php$ /nr2id/$arg_nr last;
}
```

Replacing the last rewrite by `rewrite ^/nr2id.php$ /select.php?nr=$arg_nr&nr2id=true last;` is a working configuration.

Discovered with issue https://github.com/cgeo/cgeo/issues/5931

**Comment by kumy** [comment]
cc @lepichon @romain-dartigues any idea?

**Comment by kumy** [comment]
- `rewrite ^/nr2id.php$ /select.php?nr=$arg_nr&nr2id=true last;``is active at the moment, the service is now up.
- Adding a check in monitoring.

**Comment by ghost** [comment]
rewrite_log on; # est ton ami

**Comment by kumy** [comment]
`last` parameter was the problem
